name: Run Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]
    
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            core:
              - 'Jdempotent-core/**'
            postgres:
              - 'Jdempotent-spring-boot-postgres-starter/**'
            redis:
              - 'Jdempotent-spring-boot-redis-starter/**'

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and install Jdempotent-core to local repository
        if: ${{ steps.changes.outputs.core == 'true' || steps.changes.outputs.postgres == 'true' || steps.changes.outputs.redis == 'true' }}
        run: mvn clean install -pl Jdempotent-core -DskipTests

      - name: Run tests for "Jdempotent-core"
        if: ${{ steps.changes.outputs.core == 'true' }}
        run: mvn test -pl Jdempotent-core

      - name: Run tests for "Jdempotent-spring-boot-redis-starter"
        if: ${{ steps.changes.outputs.redis == 'true' || steps.changes.outputs.core == 'true' }}
        run: mvn test -pl Jdempotent-spring-boot-redis-starter

      - name: Run tests for "Jdempotent-spring-boot-postgres-starter"
        if: ${{ steps.changes.outputs.postgres == 'true' || steps.changes.outputs.core == 'true' }}
        run: mvn test -pl Jdempotent-spring-boot-postgres-starter
