name: PR Tests (Secure)

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    # branches: [ master, main ]

jobs:
  # Check if the PR author has write permissions
  check-permissions:
    runs-on: ubuntu-latest
    outputs:
      has-permission: ${{ steps.check.outputs.has-permission }}
    steps:
      - name: Check user permissions
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const { data: permission } = await github.rest.repos.getCollaboratorPermissionLevel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                username: context.payload.pull_request.user.login
              });
              
              const hasPermission = ['admin', 'maintain', 'write'].includes(permission.permission);
              console.log(`User ${context.payload.pull_request.user.login} has permission: ${permission.permission}`);
              console.log(`Has required permission: ${hasPermission}`);
              
              core.setOutput('has-permission', hasPermission);
              return hasPermission;
            } catch (error) {
              console.log(`Error checking permissions: ${error.message}`);
              core.setOutput('has-permission', false);
              return false;
            }

  # Run tests only if user has permissions
  run-tests:
    needs: check-permissions
    if: needs.check-permissions.outputs.has-permission == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]
    
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        run: mvn clean test -B

  # Comment on PR if permission denied
  permission-denied:
    needs: check-permissions
    if: needs.check-permissions.outputs.has-permission == 'false'
    runs-on: ubuntu-latest
    
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `⚠️ **Permission Required**
            
            Tests can only be run by repository maintainers or owners. 
            
            If you're a contributor, please wait for a maintainer to review and approve your changes.
            
            **For maintainers:** You can trigger tests by:
            - Commenting \`/run-tests\` on this PR
            - Pushing a commit to approve the workflow
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
